### ISSUE TITLE
repo list keeps loading, while buttons are not disabled

### ISSUE THREAD

**Issue by rizkimcitra** [teknologi-umum/hacktoberfest#42]
This happens on me, with **no error logged to the console** neither **network tab** has problem.
![image](https://user-images.githubusercontent.com/62492410/192191574-8b97ab5e-aaaf-4d9a-8561-498a1d5dff19.png)

then when the buttons clicked, an error is displayed on view:
![image](https://user-images.githubusercontent.com/62492410/192191690-5024cfc5-2305-456b-8da0-85c5475f22c2.png)

**Comment by elianiva** [comment]
fixed, thanks for the report!
