### ISSUE TITLE
Favicon doesn't show up on Chrome (or Chrome-based browsers)

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/hacktoberfest#58]
Using Brave:
![image](https://user-images.githubusercontent.com/7274326/193447454-87737c4d-fb38-4fcf-9f72-50e527bf6795.png)

Using Chrome:
![image](https://user-images.githubusercontent.com/7274326/193447438-08c5213d-bf0d-4d29-b9ce-26cb5303771c.png)

Using Firefox (this works btw):
![image](https://user-images.githubusercontent.com/7274326/193447447-beede46f-8a5b-4f2f-abad-f37e8f73a9aa.png)

**Comment by kala2** [comment]
hello, can you assign to me please?

**Comment by aldy505** [comment]
Sure, go ahead. No need to assign the issue to you tho, anyone who read this would know that :)
