### ISSUE TITLE
Fix language logo overflow-x on mobile

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/hacktoberfest#59]
Self explanatory

![image](https://user-images.githubusercontent.com/51877647/193806656-0efc2152-a260-4469-b0b9-80c4b1c9d220.png)

**Comment by krowter** [comment]
Nitip. Main heading and repo name also overflows on mobile (tested on iPhone X)
![WhatsApp Image 2022-10-04 at 9 33 03 PM](https://user-images.githubusercontent.com/42563517/193955054-a0653bc9-e449-4169-bba0-de477036b2e6.jpg)

**Comment by elianiva** [comment]
#60
