### ISSUE TITLE
dim the white filter colour

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/hacktoberfest#73]
the white filter colour should be dimmed to make it more visible whether if it's an active filter or not, just like the other filters colour

![image](https://user-images.githubusercontent.com/51877647/196077365-4077ce41-09df-49e7-b569-a01dafe28741.png)

**Comment by aryanlath** [comment]
Hi! Can you assign this to me?

**Comment by elianiva** [comment]
#77
